scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100', 'producer:9100']

  - job_name: near-exporter
    scrape_interval: 15s
    static_configs:
    - targets: ['producer:9333'] 

  - job_name: near-node
    scrape_interval: 15s
    static_configs:
    - targets: ['producer:3030']     

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"